# Generated by Django 2.2.15 on 2020-08-23 06:06

from django.db import migrations, models
import edivorce.apps.core.redis


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=edivorce.apps.core.redis.RedisStorage(), upload_to=edivorce.apps.core.redis.generate_unique_filename),
        ),
    ]
