# Generated by Django 2.2.15 on 2020-09-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_auto_20200823_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docType',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='partyId',
            field=models.IntegerField(default=0),
        ),
    ]
