# Generated by Django 2.2.15 on 2020-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0003_auto_20200915_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
