# Generated by Django 2.2.15 on 2020-09-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200903_2328'),
        ('poc', '0004_auto_20200917_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docType',
            new_name='doc_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='partyId',
            new_name='party_id',
        ),
        migrations.AddField(
            model_name='document',
            name='bceid_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.BceidUser'),
        ),
        migrations.AddField(
            model_name='document',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('bceid_user', 'doc_type', 'party_id', 'filename', 'length')},
        ),
        migrations.RunSQL(
            sql='delete from poc_document'
        )
    ]
