# Generated by Django 2.2.15 on 2020-09-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0005_auto_20200921_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bceid_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.BceidUser'),
            preserve_default=False,
        ),
    ]
