# Generated by Django 2.2.15 on 2020-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0006_auto_20200921_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
