# Generated by Django 2.2.15 on 2020-09-22 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200903_2328'),
        ('poc', '0007_auto_20200921_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='party_id',
            new_name='party_code',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='length',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.AddField(
            model_name='document',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('bceid_user', 'doc_type', 'party_code', 'filename', 'size')},
        ),
    ]
