# Generated by Django 2.2.15 on 2020-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0008_auto_20200922_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
