# Generated by Django 2.2.15 on 2020-09-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0009_auto_20200922_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
