# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191008_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='bceiduser',
            name='is_bcsc',
            field=models.BooleanField(default=False),
        ),
    ]
