# Generated by Django 2.2.15 on 2020-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='document',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
