# Generated by Django 2.2.15 on 2020-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201009_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bceiduser',
            name='is_bcsc',
            field=models.BooleanField(default=False),
        ),
    ]
