# Generated by Django 2.2.15 on 2020-10-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201009_1235'),
        ('core', '0024_bceiduser_is_bcsc'),
        ('core', '0020_bceiduser_is_bcsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bceiduser',
            name='is_bcsc',
        ),
    ]
