# Generated by Django 2.2.15 on 2020-10-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_bceiduser_is_bcsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
