# Generated by Django 2.2.15 on 2020-11-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201028_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filing_type',
            field=models.CharField(default='i', max_length=1),
        ),
    ]
